version: "3"

services:
   server:
     image: andreferrazz/server:main
     container_name: server
     hostname: server
     ports:
       - "80:80"
       - "443:443"
     volumes:
       - /etc/letsencrypt:/etc/letsencrypt
     depends_on:
       - portfolio
       - naruto

  portfolio:
    image: andreferrazz/portfolio:main
    container_name: portfolio
    hostname: portfolio
  
  naruto:
    image: simple-web-api:latest
    container_name: naruto
    hostname: naruto
    environment:
      APP_NAME: Naruto

